title: Choral Language Website
author: <a href="/about.html#development-team">Choral Development Team</a>

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  documentation:
    output: true

documentation_menu:
  - Basics
  - Examples

menu:
  - Documentation
  - Downloads
  - About